source $HOME/my-vimrc/common.vim

set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
source $HOME/my-vimrc/linux/linuxp.vim
source $HOME/my-vimrc/nerdtreep.vim
source $HOME/my-vimrc/statusp.vim
source $HOME/my-vimrc/ycmp.vim
source $HOME/my-vimrc/coffeep.vim
source $HOME/my-vimrc/tagbarp.vim
source $HOME/my-vimrc/ctrlpp.vim 
source $HOME/my-vimrc/endwisep.vim
source $HOME/my-vimrc/alep.vim
call vundle#end()

source $HOME/my-vimrc/linux/linux.vim
source $HOME/my-vimrc/nerdtree.vim
source $HOME/my-vimrc/status.vim
source $HOME/my-vimrc/ycm.vim
source $HOME/my-vimrc/coffee.vim 
source $HOME/my-vimrc/tagbar.vim
source $HOME/my-vimrc/ctrlp.vim
source $HOME/my-vimrc/endwise.vim
source $HOME/my-vimrc/ale.vim
